### ISSUE TITLE
I am done with the wiki!

### ISSUE THREAD

**Issue by Wjplatformer** [LogSkele/gitcollect#11]
You can go to my fork and [clone](https://github.com/Wjplatformer/gitcollect.wiki.git) it!

**Comment by LogSkele** [comment]
nevermind, cloned it.

**Comment by LogSkele** [comment]
look at the new wiki :D https://github.com/LogSkele/gitcollect/wiki

**Comment by Wjplatformer** [comment]
Yeaaah!!
