### ISSUE TITLE
How to navigate

### ISSUE THREAD

**Issue by Wjplatformer** [LogSkele/gitcollect#6]
After countless hours of searching through inspect on my github page, tinkering with bs4 and looking at bs4 documentation, I have no idea on how you got those data from github `e = soup.find(class_="f4 my-3").get_text()`<br><br>
![image](https://user-images.githubusercontent.com/82447031/174602623-57c9acf9-0824-4cc6-b651-9734fd724e43.png)

**Comment by LogSkele** [comment]
haha i just looked at the class name, and so happened it is `f4 my-3`. don't ask. it isn't professional but it works lol

**Comment by Wjplatformer** [comment]
alright then.
